name: ISO

on:
  workflow_dispatch:
    inputs:
      zip_location:
        required: true
      sessionID:
        required: true

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Archlinux
      run: curl -L https://github.com/jovarkos/github-actions-archlinux/raw/master/install.sh | bash
    - name: Docker hello-world
      run: |
        sudo pacman --noconfirm -Syu docker
        sudo systemctl start docker
        docker run --rm hello-world
